export const MICRO_ACTIONS_LIBRARY = [
  {
    id: "prep_focus_outline",
    title: "Clarifie le projet en 1 phrase",
    subtitle: "Définis ce qui compte vraiment.",
    durationMin: 3,
    categoryId: "general",
    intent: "prep",
    tags: ["clarify", "focus"],
  },
  {
    id: "prep_next_step",
    title: "Écris la prochaine action",
    durationMin: 3,
    categoryId: "general",
    intent: "prep",
    tags: ["next-step"],
  },
  {
    id: "prep_workspace",
    title: "Prépare ton espace",
    durationMin: 2,
    categoryId: "general",
    intent: "prep",
    tags: ["setup"],
  },
  {
    id: "exec_start_small",
    title: "Lance une action de 5 min",
    durationMin: 5,
    categoryId: "general",
    intent: "execute",
    tags: ["start"],
  },
  {
    id: "exec_momentum",
    title: "Avance 3 min sans t’arrêter",
    durationMin: 3,
    categoryId: "general",
    intent: "execute",
    tags: ["momentum"],
  },
  {
    id: "review_progress",
    title: "Note 1 progrès du jour",
    durationMin: 2,
    categoryId: "general",
    intent: "review",
    tags: ["review"],
  },
  {
    id: "planning_check_time",
    title: "Vérifie l’heure et le lieu",
    durationMin: 2,
    categoryId: "planning",
    intent: "prep",
    tags: ["planning", "check"],
  },
  {
    id: "planning_open_doc",
    title: "Ouvre le doc ou le lien",
    durationMin: 2,
    categoryId: "planning",
    intent: "prep",
    tags: ["planning", "open"],
  },
  {
    id: "planning_outline",
    title: "Liste 3 points à couvrir",
    durationMin: 4,
    categoryId: "planning",
    intent: "prep",
    tags: ["planning", "outline"],
  },
  {
    id: "review_checklist",
    title: "Relis ton plan rapide",
    durationMin: 3,
    categoryId: "planning",
    intent: "review",
    tags: ["planning", "review"],
  },
  {
    id: "prep_call",
    title: "Prépare 3 points clés",
    durationMin: 3,
    categoryId: "business",
    intent: "prep",
    tags: ["meeting", "outline"],
    matchers: { actionTitleIncludes: ["appel", "call", "meeting", "réunion"] },
  },
  {
    id: "prep_pitch",
    title: "Liste 3 objections possibles",
    durationMin: 4,
    categoryId: "business",
    intent: "prep",
    tags: ["pitch", "objections"],
    matchers: { actionTitleIncludes: ["pitch", "vente", "présentation", "presentation"] },
  },
  {
    id: "exec_email",
    title: "Écris l’objet + 1er paragraphe",
    durationMin: 4,
    categoryId: "business",
    intent: "execute",
    tags: ["writing", "email"],
    matchers: { actionTitleIncludes: ["email", "mail"] },
  },
  {
    id: "exec_followup",
    title: "Envoie un message court de suivi",
    durationMin: 3,
    categoryId: "business",
    intent: "execute",
    tags: ["followup"],
  },
  {
    id: "prep_kpi",
    title: "Clarifie le KPI du jour",
    durationMin: 3,
    categoryId: "business",
    intent: "prep",
    tags: ["kpi", "focus"],
  },
  {
    id: "review_business",
    title: "Relis le doc principal 4 min",
    durationMin: 4,
    categoryId: "business",
    intent: "review",
    tags: ["review", "reading"],
  },
  {
    id: "prep_workout",
    title: "Prépare tenue + eau",
    durationMin: 2,
    categoryId: "sante",
    intent: "prep",
    tags: ["hydration", "setup"],
    timeOfDay: "morning",
    matchers: { actionTitleIncludes: ["sport", "entraînement", "training", "run", "course"] },
  },
  {
    id: "exec_breath",
    title: "Respire 10 fois lentement",
    durationMin: 3,
    categoryId: "sante",
    intent: "execute",
    tags: ["breath"],
  },
  {
    id: "exec_walk",
    title: "Marche 5 min",
    durationMin: 5,
    categoryId: "sante",
    intent: "execute",
    tags: ["walk"],
  },
  {
    id: "exec_stretch",
    title: "Étire nuque + épaules",
    durationMin: 3,
    categoryId: "sante",
    intent: "execute",
    tags: ["stretch"],
  },
  {
    id: "review_energy",
    title: "Note ton énergie (1-5)",
    durationMin: 2,
    categoryId: "sante",
    intent: "review",
    tags: ["review", "energy"],
  },
];
