export const SURFACE_LABELS = Object.freeze({
  today: "Aujourd'hui",
  planning: "Planning",
  library: "Objectifs",
  pilotage: "Analyses",
  coach: "Coach",
  session: "Session",
  journal: "Journal",
  history: "Historique",
  settings: "Réglages",
  account: "Compte",
  subscription: "Abonnement",
  privacy: "Confidentialité",
  legal: "Conditions",
});

export const MAIN_PAGE_COPY = Object.freeze({
  today: Object.freeze({
    orientation: "Ton prochain pas utile, clairement mis en avant.",
    nextActionsSubtitle: "Actions recommandées pour aujourd'hui.",
    dailyStateTitle: "État du jour",
    dailyStateSubtitle: "Prévu, fait, restant.",
  }),
  planning: Object.freeze({
    orientation: "Ta feuille de route d'exécution.",
    weekDescription: "Une vue claire des blocs terminés et à venir.",
    dayDescription: "Une vue claire des blocs terminés et à venir.",
  }),
  library: Object.freeze({
    orientation: "Une structure par objectifs avec les actions liées en dessous.",
    primaryTitle: "Objectifs",
    reclassifyTitle: "Masqué pour cette direction",
    suggestionsTitle: "Structure suggérée",
  }),
  pilotage: Object.freeze({
    orientation: "Ta trajectoire cette semaine.",
    summaryTitle: "Vue d'ensemble",
    focusTitle: "Focus",
    statsTitle: "Signaux",
  }),
});

export const TAB_COPY = Object.freeze({
  today: SURFACE_LABELS.today,
  objectives: SURFACE_LABELS.library,
  timeline: SURFACE_LABELS.planning,
  insights: SURFACE_LABELS.pilotage,
  coach: SURFACE_LABELS.coach,
});

export const CREATE_MENU_COPY = Object.freeze({
  menuAriaLabel: "Capture universelle",
  openMenu: "Créer",
  promptTitle: "Qu’est-ce que tu veux faire avancer ?",
  inputPlaceholder: "Décris ton intention en une phrase.",
  submitLabel: "Continuer",
  previewActionLabel: "Action",
  previewGoalLabel: "Objectif",
  previewCreateLabel: "Créer",
  previewAdjustLabel: "Ajuster",
  resumeDraftLabel: "Reprendre le brouillon",
  resumeDraftMeta: "Continuer la création en cours",
});

export const TODAY_SCREEN_COPY = Object.freeze({
  insightTitle: "Analyse IA",
  priorityTitle: "Priorité principale",
  actionsTitle: "Alternatives",
  actionsSubtitle: "Deux options utiles, pas plus.",
  profileAriaLabel: "Ouvrir le menu profil",
  profileMenuTitle: "Profil",
  profileMenuSubtitle: "Accès rapide aux surfaces secondaires.",
  profileRouteAccount: "Profil",
  profileRouteBilling: "Abonnement",
  profileRouteSettings: "Réglages",
  profileRouteFaq: "FAQ",
  profileRouteLegal: "Légal",
  createWithCoach: "Créer avec le coach",
  quote: "Les petites actions régulières produisent des résultats extraordinaires.",
  greetingMorning: "Bonjour",
  greetingEvening: "Bonsoir",
  fallbackName: "toi",
  welcomeMorningSubtitle: "On garde un seul bon prochain pas en vue.",
  welcomeDaySubtitle: "Ton cockpit du jour, sans bruit inutile.",
  welcomeEveningSubtitle: "On termine proprement ce qui compte encore.",
  welcomeReadySubtitle: "Ton prochain bloc est prêt à être lancé.",
  welcomeClarifySubtitle: "On remet un seul prochain pas au centre.",
  welcomeOverloadSubtitle: "On allège pour garder une journée crédible.",
  welcomeValidatedSubtitle: "L’essentiel est déjà fait aujourd’hui.",
  welcomeFallbackSubtitle: "Une lecture claire de la journée suffit pour avancer.",
  progressTitle: "Progression du jour",
  progressBlocksLabel: "Blocs validés",
  progressMinutesLabel: "Temps exécuté",
  progressNextLabel: "Prochain bloc",
  progressNothingReady: "Rien de prêt",
  heroStateReady: "Prêt",
  heroStateSession: "Session",
  heroStateClarify: "À clarifier",
  heroStateOverload: "À alléger",
  heroStateValidated: "Validé",
  heroStateFallback: "Repère du jour",
  heroGuideReady: "Le prochain pas mérite toute la place.",
  heroGuideClarify: "Clarifie avant d’ajouter de la complexité.",
  heroGuideOverload: "Réduis d’abord, puis relance proprement.",
  heroGuideValidated: "Protège l’élan sans rallonger la journée.",
  heroGuideFallback: "Le focus du jour doit rester lisible.",
  resumeSessionTitle: "Reprendre la session en cours",
  resumeSessionAction: "Reprendre la session",
  valuePulseFallbackTitle: "Le rythme du jour se construit par des blocs crédibles.",
  valuePulseFallbackMeta: "Garde la journée simple, claire et exécutable.",
  primaryAction: "Démarrer",
  preparingTitle: "Préparation du prochain pas",
  preparingReason: "Lecture de ton contexte actuel.",
  noPriorityTitle: "Aucune priorité claire pour aujourd'hui",
  noPriorityReason: "Aucune priorité nette n'est disponible pour le moment.",
  noReadyActionTitle: "Aucune action prévue aujourd'hui",
  noReadyActionReason: "Commence dans Objectifs avec une structure claire puis une première action.",
  priorityCategoryFallback: "Priorité principale",
  emptyActionsTitle: "Aucune autre action recommandée aujourd'hui.",
  emptyActionsCopy: "Le reste de la journée reste volontairement dégagé pour garder un rythme lisible.",
  actionFallback: "Action",
  clarifyTitle: "Rien de net pour maintenant",
  clarifyReason: "Aucun prochain bloc crédible ne ressort pour maintenant.",
  clarifyNextBlock: "Clarifier mon prochain bloc",
  createAction: "Créer une action",
  overloadTitle: "La journée est trop chargée",
  overloadReason: "La charge du jour dépasse ce qui semble crédible.",
  relieveDay: "Alléger ma journée",
  reviewPlanning: "Revoir mon planning",
  validatedTitle: "Journée validée",
  validatedReason: "L’essentiel du jour est terminé.",
  prepareNextStep: "Préparer le prochain pas",
});

export const OBJECTIVES_SCREEN_COPY = Object.freeze({
  title: SURFACE_LABELS.library,
  createAriaLabel: "Créer",
  allCategories: "Toutes",
  categoryFilterLabel: "Filtrer par catégorie",
  untitledObjective: "Objectif sans titre",
  untitledAction: "Action sans titre",
  fallbackSubtitle: "Exécution liée juste en dessous.",
  deadlinePrefix: "Échéance",
  standaloneSuffix: "actions",
  standaloneTitle: "Actions non liées",
  standaloneSubtitle: "Actions encore non rattachées à un objectif.",
  noLinkedActions: "Aucune action liée pour le moment.",
  activeActions: "Actions actives",
  todayActions: "Aujourd'hui",
  upcomingActions: "À venir",
  noActiveActions: "Aucune action active pour le moment.",
  noTodayActions: "Rien de prévu aujourd'hui.",
  noUpcomingActions: "Rien à venir pour l'instant.",
  editObjective: "Modifier l'objectif",
  addAction: "Ajouter une action",
  emptyTitle: "Aucun objectif pour l'instant.",
  emptyCopy: "Crée ton premier objectif pour structurer le travail réel dans cette vue.",
});

export const TIMELINE_SCREEN_COPY = Object.freeze({
  title: SURFACE_LABELS.planning,
  subtitle: MAIN_PAGE_COPY.planning.orientation,
  allCategories: "Toutes",
  categoryFilterLabel: "Filtrer par catégorie",
  entryFallbackTitle: "Bloc d'exécution",
  completed: "Terminée",
  upcoming: "À venir",
  backToToday: "Revenir à aujourd'hui",
  selectDate: "Choisir une date",
  selectedDateLabel: "Jour affiché",
  inlineDuration: "Durée",
  inlineCategory: "Catégorie",
  inlineObjective: "Objectif lié",
  inlineNotes: "Notes",
  inlineStatus: "Statut",
  inlineNoCategory: "Aucune catégorie liée.",
  inlineNoNotes: "Aucune note pour ce bloc.",
  inlineNoObjective: "Aucun objectif lié.",
  inlineEditAction: "Modifier l'action",
  inlineEditObjective: "Modifier l'objectif",
  inlineStartSession: "Démarrer la session",
  inlineResumeSession: "Reprendre la session active",
  recurringLabel: "Récurrent",
  recurringSummaryFallback: "Rythme récurrent à venir",
  recurringOccurrences: "Prochaines échéances",
  recurringNoUpcoming: "Aucune prochaine échéance visible.",
  calendarAriaLabel: "Vue calendrier",
  calendarTitle: "Choisir un jour",
  calendarSubtitle: "Affiche les blocs du jour choisi, puis le proche à venir.",
  expand: "Déplier",
  collapse: "Replier",
});

export const INSIGHTS_SCREEN_COPY = Object.freeze({
  title: SURFACE_LABELS.pilotage,
  subtitle: MAIN_PAGE_COPY.pilotage.orientation,
  streak: "Série",
  completion: "Complétion",
  momentum: "Dynamique",
  focusScore: "Score de concentration",
  coachReading: "Lecture du coach",
  directionTitle: "Direction recommandée",
  patternDetected: "Signal détecté",
  weeklyNarrative: "Lecture hebdomadaire",
  graphLegend: "Score = actions prévues terminées / actions prévues du jour.",
  coachAnalysisCta: "Analyse du coach",
  coachAnalysisRetry: "Relancer l'analyse",
  fallbackCoachReading: "Lecture locale disponible tant qu'aucune analyse du coach n'a été générée.",
  loadingFallback: "Analyse en cours…",
  graphPointTitle: "Détail du jour",
  graphDateLabel: "Date",
  graphScoreLabel: "Score",
  graphCompletedLabel: "Complétées",
  graphPlannedLabel: "Prévues",
  graphNoPlanExplanation: "Aucune action planifiée ce jour-là.",
  graphAllDoneExplanation: "Toutes les actions prévues ont été complétées.",
  graphPartialExplanation: "Une partie des actions prévues a été complétée.",
  graphNoneDoneExplanation: "Aucune action prévue n'a été complétée.",
  directions: Object.freeze({
    maintain: "Maintenir",
    recalibrate: "Recalibrer",
    accelerate: "Accélérer",
    lighten: "Alléger",
  }),
  trendLabels: Object.freeze({
    hausse: "En hausse",
    baisse: "En baisse",
    irregularite: "Irrégulière",
    stable: "Stable",
  }),
});

export const COACH_SCREEN_COPY = Object.freeze({
  title: SURFACE_LABELS.coach,
  subtitle: "Ton copilote stratégique",
  structuringModeLabel: "Structurer",
  quickCreateLabel: "Créer vite",
  contextualIntentLabel: "Contexte",
  workTrayDismiss: "Annuler",
  composerMenuAriaLabel: "Intentions du coach",
  composerPlusAriaLabel: "Ouvrir les intentions du coach",
  structuringPrefill: "Aide-moi à structurer ce que je veux faire avancer.",
  quickCreatePrefill: "Aide-moi à transformer vite cette intention en brouillon concret.",
  structuringMenuDescription: "Clarifier et mettre en forme dans le coach.",
  quickCreateMenuDescription: "Transformer vite une intention en brouillon.",
  introEyebrow: "Coach",
  introMessage: "Bonjour {name}. Je suis ton coach IA pour t'aider à rester clair, concentré et en mouvement.\n\nQu'est-ce qui compte pour toi aujourd'hui ?",
  userEyebrow: "Toi",
  assistantEyebrow: "Coach",
  draftTitle: "Proposition structurée",
  draftCategoryLabel: "Catégorie",
  draftObjectiveLabel: "Objectif",
  draftActionFallback: "Action",
  create: "Créer",
  creating: "Création…",
  created: "Créé",
  reviewInApp: "Voir dans l'app",
  thinking: "Réflexion en cours…",
  placeholder: "Demande au coach ce dont tu as besoin…",
  sendAriaLabel: "Envoyer",
  concisePlanTitle: "Plan proposé",
  unresolvedTitle: "À confirmer",
  categoryClarificationPrompt: "Dans quelle catégorie veux-tu avancer ?",
});

export const CATEGORY_UI_COPY = Object.freeze({
  fieldLabel: "Catégorie",
  currentTitle: "Catégorie actuelle",
  suggestedTitle: "Catégorie suggérée",
  newCategory: "Nouvelle catégorie",
  newCategoryPlaceholder: "Nom de la catégorie",
  createCategory: "Créer",
  cancelCreateCategory: "Annuler",
  duplicateNameError: "Une catégorie avec ce nom existe déjà.",
  emptyNameError: "Donne un nom à la catégorie.",
});

export const LABELS = Object.freeze({
  goal: "Objectif",
  goals: "Objectifs",
  goalLower: "objectif",
  goalsLower: "objectifs",
  action: "Action",
  actions: "Actions",
  actionLower: "action",
  actionsLower: "actions",
});

export const UI_COPY = Object.freeze({
  save: "Enregistrer",
  close: "Fermer",
  cancel: "Annuler",
  continue: "Continuer",
  done: "Fait",
  watchAd: "Regarder une vidéo",
  openPlanning: "Régler le rythme",
  refreshAnalysis: "Relire la situation",
  analyzePriority: "Observer ma situation",
  backToLocalDiagnostic: "Revenir à la lecture locale",
  openSupport: "Contacter le support",
  restorePurchases: "Restaurer mes achats",
  discoverPremium: "Découvrir Premium",
  openMailbox: "Ouvrir ma messagerie",
  resendLink: "Renvoyer le lien",
  coachAnalysis: "Analyse du coach",
  rerunCoachAnalysis: "Relancer l'analyse",
  openObjectives: "Ouvrir Objectifs",
});

export const ANALYSIS_COPY = Object.freeze({
  localDiagnostic: "Lecture locale",
  coachAnalysis: "Lecture du coach",
  coachAnalysisUpdated: "Lecture du coach mise à jour",
  coachBadge: "Coach",
  coachLoadingHint: "Lecture du coach en cours",
  guardedRecommendation: "Repère prioritaire",
  savedOnDevice: "Enregistrée sur cet appareil",
  syncedAcrossDevices: "Synchronisée sur tes appareils",
});

export const PLACEHOLDER_COPY = Object.freeze({
  whyText: "Décris la raison que tu veux garder en vue quand la discipline baisse.",
  accountHandle: "Choisis un identifiant public, si tu veux en afficher un.",
  fullName: "Nom complet, si tu veux le renseigner.",
  avatarUrl: "Lien direct vers une image de profil.",
  outcomeTitle: "Nom de l’objectif",
  notes: "Ajoute le contexte utile, sans te noyer dans les détails.",
});

export const STATUS_COPY = Object.freeze({
  checking: "Vérification en cours…",
  saving: "Enregistrement…",
  loading: "Chargement…",
  refreshing: "Actualisation…",
  importDone: "Import terminé.",
  importInvalid: "Import impossible : le fichier JSON est invalide.",
  importReadError: "Import impossible : le fichier n’a pas pu être lu.",
});

export const MARKETING_COPY = Object.freeze({
  essentialPlan: "Accès essentiel",
  premiumPlan: "Premium actif",
  premiumSubtitle: "Débloque toute la structure de l’app, le Coach et l’historique complet.",
  premiumLimitsPrefix: "Limites actuelles",
});
