import { LABELS } from "../ui/labels";
// FIRST_USE_TOUR rationale:
// - Minimal first-use tour designed for an empty app state (no categories).
// - Anchors are guaranteed to exist on Today empty state only.
// - Deeper navigation (Library/Create/Manage/Pilotage/Settings) is handled later.
// - Uses a safe lookup to avoid crashes if anchors are missing.
export const TOUR_VERSION = 1;

export const TOUR_STEPS = [
  // Today cockpit
  {
    id: "topnav-tabs",
    screen: "today",
    anchor: "topnav-tabs",
    title: "Navigation",
    body: "Passe de Today à Objectifs, Planning, Coach IA ou Ajuster.",
    placement: "bottom",
    nextActionHint: "Regarde les raccourcis.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "today-title",
    screen: "today",
    anchor: "today-title",
    title: "Aujourd’hui",
    body: "Ton tableau de bord du jour.",
    placement: "bottom",
    nextActionHint: "Fais défiler.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "today-hero-card",
    screen: "today",
    anchor: "today-hero-card",
    title: "Diagnostic",
    body: "Le cockpit résume l’état de ta journée.",
    placement: "top",
    nextActionHint: "Lis le score.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-primary-action-card",
    screen: "today",
    anchor: "today-primary-action-card",
    title: "Bloc principal",
    body: "C’est l’action à protéger maintenant.",
    placement: "top",
    nextActionHint: "Verrouille ou ajuste.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-timeline-card",
    screen: "today",
    anchor: "today-timeline-card",
    title: "Timeline",
    body: "Explore les blocs du jour sans ouvrir une grande vue.",
    placement: "top",
    nextActionHint: "Fais défiler si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-ai-insight-card",
    screen: "today",
    anchor: "today-ai-insight-card",
    title: "Coach IA",
    body: "L’IA propose un ajustement seulement quand un signal existe.",
    placement: "top",
    nextActionHint: "Ouvre Coach IA si utile.",
    skippableAfterMs: 3000,
  },

  // Library
  {
    id: "library-title",
    screen: "library",
    anchor: "library-title",
    title: "Bibliotheque",
    body: "Tout ton contenu est ici.",
    placement: "bottom",
    nextActionHint: "Parcours la liste.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "library-manage",
    screen: "library",
    anchor: "library-category-list",
    title: "Gérer",
    body: "Ouvre la gestion détaillée.",
    placement: "bottom",
    nextActionHint: "Ouvre Gérer.",
    skippableAfterMs: 3000,
  },
  {
    id: "library-category-list",
    screen: "library",
    anchor: "library-category-list",
    title: "Catégories",
    body: "Sélectionne une catégorie.",
    placement: "top",
    nextActionHint: "Clique une carte.",
    skippableAfterMs: 3000,
  },

  // Manage
  {
    id: "manage-title",
    screen: "manage",
    anchor: "manage-title",
    title: "Gérer",
    body: "Détails d’une catégorie.",
    placement: "bottom",
    nextActionHint: "Regarde l’en-tête.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-name",
    screen: "manage",
    anchor: "manage-category-name",
    title: "Catégorie",
    body: "Nom de la catégorie active.",
    placement: "bottom",
    nextActionHint: "Identifie la catégorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-back",
    screen: "manage",
    anchor: "manage-back",
    title: "Retour",
    body: "Reviens à la bibliothèque.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-card",
    screen: "manage",
    anchor: "manage-category-card",
    title: "Paramètres",
    body: "Infos de la catégorie.",
    placement: "top",
    nextActionHint: "Ouvre les parametres.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-settings",
    screen: "manage",
    anchor: "manage-category-settings",
    title: "Réglages catégorie",
    body: "Ouvre les actions rapides.",
    placement: "left",
    nextActionHint: "Ouvre le menu.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-rename",
    screen: "manage",
    anchor: "manage-category-rename",
    title: "Renommer",
    body: "Change le nom.",
    placement: "right",
    nextActionHint: "Renomme si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-priority",
    screen: "manage",
    anchor: "manage-category-priority",
    title: "Prioritaire",
    body: "Définis la priorité.",
    placement: "right",
    nextActionHint: "Définis la priorité.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-delete",
    screen: "manage",
    anchor: "manage-category-delete",
    title: "Supprimer",
    body: "Action irréversible.",
    placement: "left",
    nextActionHint: "Utilise avec prudence.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-mini-why",
    screen: "manage",
    anchor: "manage-mini-why",
    title: "Mini-why",
    body: "Pourquoi de la catégorie.",
    placement: "top",
    nextActionHint: "Lis ou modifie.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-mini-why-toggle",
    screen: "manage",
    anchor: "manage-mini-why-toggle",
    title: "Afficher",
    body: "Montre ou masque le mini-why.",
    placement: "left",
    nextActionHint: "Toggle si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-objectives-section",
    screen: "manage",
    anchor: "manage-objectives-section",
    title: LABELS.goals,
    body: `Liste des ${LABELS.goalsLower}.`,
    placement: "top",
    nextActionHint: `Ouvre un ${LABELS.goalLower}.`,
    skippableAfterMs: 3000,
  },
  {
    id: "manage-actions-section",
    screen: "manage",
    anchor: "manage-actions-section",
    title: "Actions",
    body: "Liste des actions.",
    placement: "top",
    nextActionHint: "Ouvre une action.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-pilotage-section",
    screen: "manage",
    anchor: "manage-pilotage-section",
    title: "Pilotage",
    body: "Ouvre la vue d'ensemble.",
    placement: "top",
    nextActionHint: "Va sur Pilotage.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-open-pilotage",
    screen: "manage",
    anchor: "manage-open-pilotage",
    title: "Ouvrir pilotage",
    body: "Acces a la page Pilotage.",
    placement: "bottom",
    nextActionHint: "Ouvre Pilotage.",
    skippableAfterMs: 3000,
  },

  // Pilotage
  {
    id: "pilotage-title",
    screen: "pilotage",
    anchor: "pilotage-title",
    title: "Pilotage",
    body: "Resume global.",
    placement: "bottom",
    nextActionHint: "Regarde les sections.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-category-status",
    screen: "pilotage",
    anchor: "pilotage-category-status",
    title: "État des catégories",
    body: "Liste et statut.",
    placement: "top",
    nextActionHint: "Lis une ligne.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-load",
    screen: "pilotage",
    anchor: "pilotage-load",
    title: "Charge",
    body: "Planifié vs terminé.",
    placement: "top",
    nextActionHint: "Lis les chiffres.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-planifier-empty",
    screen: "pilotage",
    anchor: "pilotage-load",
    title: "Planifier",
    body: "Action rapide si rien n'est planifie.",
    placement: "left",
    nextActionHint: "Ouvre la creation.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-discipline",
    screen: "pilotage",
    anchor: "pilotage-discipline",
    title: "Discipline",
    body: "Indicateurs sur 7 jours.",
    placement: "top",
    nextActionHint: "Observe les valeurs.",
    skippableAfterMs: 3000,
  },

  // Settings
  {
    id: "settings-title",
    screen: "settings",
    anchor: "settings-title",
    title: "Reglages",
    body: "Parametres de l'app.",
    placement: "bottom",
    nextActionHint: "Fais defiler.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "settings-theme",
    screen: "settings",
    anchor: "settings-theme",
    title: "Theme",
    body: "Change l'ambiance visuelle.",
    placement: "top",
    nextActionHint: "Choisis un theme.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-why",
    screen: "settings",
    anchor: "settings-why",
    title: "Pourquoi",
    body: "Modifie ton engagement.",
    placement: "top",
    nextActionHint: "Edite ton pourquoi.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-replay-onboarding",
    screen: "settings",
    anchor: "settings-replay-onboarding",
    title: "Revoir l'intro",
    body: "Relance l'onboarding.",
    placement: "top",
    nextActionHint: "Relance l'intro.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-restart-tutorial",
    screen: "settings",
    anchor: "settings-restart-tutorial",
    title: "Relancer le tutoriel",
    body: "Rejoue le guide in-app.",
    placement: "top",
    nextActionHint: "Relance le tutoriel.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-notifications",
    screen: "settings",
    anchor: "settings-notifications",
    title: "Notifications",
    body: "Infos sur les alertes.",
    placement: "top",
    nextActionHint: "Lis l'information.",
    skippableAfterMs: 3000,
  },
];

const FIRST_USE_TOUR_STEP_IDS = [
  "today-title",
  "today-empty-create-category",
];

export const FIRST_USE_TOUR_STEPS = FIRST_USE_TOUR_STEP_IDS
  .map((id) => TOUR_STEPS.find((step) => step.id === id))
  .filter(Boolean);
