// FIRST_USE_TOUR rationale:
// - Minimal first-use tour designed for an empty app state (no categories).
// - Anchors are guaranteed to exist on Today empty state only.
// - Deeper navigation (Library/Create/Manage/Pilotage/Settings) is handled later.
// - Uses a safe lookup to avoid crashes if anchors are missing.
export const TOUR_VERSION = 1;

export const TOUR_STEPS = [
  // Today (includes global nav)
  {
    id: "topnav",
    screen: "today",
    anchor: "topnav",
    title: "Navigation",
    body: "Voici la barre principale.",
    placement: "bottom",
    nextActionHint: "Regarde les onglets.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-tabs",
    screen: "today",
    anchor: "topnav-tabs",
    title: "Onglets",
    body: "Acces rapide aux sections.",
    placement: "bottom",
    nextActionHint: "Tape un onglet.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-tab-today",
    screen: "today",
    anchor: "topnav-tab-today",
    title: "Aujourd'hui",
    body: "C'est ton espace du jour.",
    placement: "bottom",
    nextActionHint: "Reste ici.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-tab-library",
    screen: "today",
    anchor: "topnav-tab-library",
    title: "Bibliotheque",
    body: "Toutes tes categories et objectifs.",
    placement: "bottom",
    nextActionHint: "Ouvre la Bibliotheque.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-tab-pilotage",
    screen: "today",
    anchor: "topnav-tab-pilotage",
    title: "Pilotage",
    body: "Vue d'ensemble et charge.",
    placement: "bottom",
    nextActionHint: "Ouvre Pilotage plus tard.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-settings",
    screen: "today",
    anchor: "topnav-settings",
    title: "Reglages",
    body: "Accede aux options.",
    placement: "left",
    nextActionHint: "Ouvre Reglages plus tard.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-rail",
    screen: "today",
    anchor: "topnav-rail",
    title: "Categories",
    body: "Selectionne une categorie ici.",
    placement: "bottom",
    nextActionHint: "Choisis une categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "topnav-category-add",
    screen: "today",
    anchor: "topnav-category-add",
    title: "Ajouter",
    body: "Cree une nouvelle categorie.",
    placement: "bottom",
    nextActionHint: "Tape pour creer.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-title",
    screen: "today",
    anchor: "today-title",
    title: "Aujourd'hui",
    body: "Ton tableau de bord du jour.",
    placement: "bottom",
    nextActionHint: "Fais defiler.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "today-subtitle",
    screen: "today",
    anchor: "today-subtitle",
    title: "Execution",
    body: "On passe a l'action.",
    placement: "bottom",
    nextActionHint: "Continue.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-empty-subtitle",
    screen: "today",
    anchor: "today-empty-subtitle",
    title: "Aucune categorie",
    body: "Ce message apparait si tout est vide.",
    placement: "bottom",
    nextActionHint: "Passe a la creation.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-empty-create-category",
    screen: "today",
    anchor: "today-empty-create-category",
    title: "Creer une categorie",
    body: "Demarre par une categorie.",
    placement: "bottom",
    nextActionHint: "Tape pour creer.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-why-text",
    screen: "today",
    anchor: "today-why-text",
    title: "Pourquoi",
    body: "Ton engagement du jour.",
    placement: "top",
    nextActionHint: "Lis cette phrase.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-why-toggle",
    screen: "today",
    anchor: "today-why-toggle",
    title: "Masquer",
    body: "Affiche ou masque le pourquoi.",
    placement: "left",
    nextActionHint: "Teste le bouton.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-stats-day",
    screen: "today",
    anchor: "today-stats-day",
    title: "Progression",
    body: "Resume du jour.",
    placement: "left",
    nextActionHint: "Ouvre les stats.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-stats-discipline",
    screen: "today",
    anchor: "today-stats-discipline",
    title: "Discipline",
    body: "Indicateur long terme.",
    placement: "left",
    nextActionHint: "Ouvre les stats.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-focus-card",
    screen: "today",
    anchor: "today-focus-card",
    title: "Focus du jour",
    body: "Choisis la cible principale.",
    placement: "top",
    nextActionHint: "Regarde cette zone.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-focus-category",
    screen: "today",
    anchor: "today-focus-category",
    title: "Categorie active",
    body: "La categorie selectionnee.",
    placement: "top",
    nextActionHint: "Verifie la categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-focus-goal-select",
    screen: "today",
    anchor: "today-focus-goal-select",
    title: "Objectif principal",
    body: "Choisis un objectif.",
    placement: "top",
    nextActionHint: "Selectionne un objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-go",
    screen: "today",
    anchor: "today-go",
    title: "GO",
    body: "Lance la session.",
    placement: "top",
    nextActionHint: "Demarre la session.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-card",
    screen: "today",
    anchor: "today-calendar-card",
    title: "Calendrier",
    body: "Navigation par date.",
    placement: "top",
    nextActionHint: "Ouvre un jour.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-today",
    screen: "today",
    anchor: "today-calendar-today",
    title: "Aujourd'hui",
    body: "Retour rapide a la date du jour.",
    placement: "bottom",
    nextActionHint: "Tape pour revenir.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-day",
    screen: "today",
    anchor: "today-calendar-day",
    title: "Vue jour",
    body: "Affiche la barre journaliere.",
    placement: "bottom",
    nextActionHint: "Passe en jour.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-month",
    screen: "today",
    anchor: "today-calendar-month",
    title: "Vue mois",
    body: "Affiche la grille mensuelle.",
    placement: "bottom",
    nextActionHint: "Passe en mois.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-rail",
    screen: "today",
    anchor: "today-calendar-rail",
    title: "Jours",
    body: "Selectionne une date.",
    placement: "top",
    nextActionHint: "Choisis un jour.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-month-grid",
    screen: "today",
    anchor: "today-calendar-month-grid",
    title: "Grille",
    body: "Selectionne un jour dans le mois.",
    placement: "top",
    nextActionHint: "Clique un jour.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-calendar-add-occurrence",
    screen: "today",
    anchor: "today-calendar-add-occurrence",
    title: "Ajouter",
    body: "Ajoute une occurrence.",
    placement: "bottom",
    nextActionHint: "Ajoute une occurrence.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-micro-card",
    screen: "today",
    anchor: "today-micro-card",
    title: "Micro-actions",
    body: "Petites actions rapides.",
    placement: "top",
    nextActionHint: "Ouvre le bloc.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-micro-toggle",
    screen: "today",
    anchor: "today-micro-toggle",
    title: "Deplier",
    body: "Affiche ou masque la liste.",
    placement: "left",
    nextActionHint: "Deplie le bloc.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-notes-card",
    screen: "today",
    anchor: "today-notes-card",
    title: "Note du jour",
    body: "Ecris ton suivi personnel.",
    placement: "top",
    nextActionHint: "Ecris une note.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-notes-text",
    screen: "today",
    anchor: "today-notes-text",
    title: "Note libre",
    body: "Une remarque rapide.",
    placement: "top",
    nextActionHint: "Saisis un texte.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-notes-meta",
    screen: "today",
    anchor: "today-notes-meta",
    title: "Check-in",
    body: "Etat rapide en 3 champs.",
    placement: "top",
    nextActionHint: "Remplis un champ.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-notes-add",
    screen: "today",
    anchor: "today-notes-add",
    title: "Ajouter",
    body: "Enregistre dans l'historique.",
    placement: "left",
    nextActionHint: "Ajoute la note.",
    skippableAfterMs: 3000,
  },
  {
    id: "today-notes-history",
    screen: "today",
    anchor: "today-notes-history",
    title: "Historique",
    body: "Accede aux notes passees.",
    placement: "left",
    nextActionHint: "Ouvre l'historique.",
    skippableAfterMs: 3000,
  },

  // Library
  {
    id: "library-title",
    screen: "library",
    anchor: "library-title",
    title: "Bibliotheque",
    body: "Tout ton contenu est ici.",
    placement: "bottom",
    nextActionHint: "Parcours la liste.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "library-manage",
    screen: "library",
    anchor: "library-manage",
    title: "Gerer",
    body: "Ouvre la gestion detaillee.",
    placement: "bottom",
    nextActionHint: "Ouvre Gerer.",
    skippableAfterMs: 3000,
  },
  {
    id: "library-create",
    screen: "library",
    anchor: "library-create",
    title: "Creer",
    body: "Demarre une creation.",
    placement: "bottom",
    nextActionHint: "Tape pour creer.",
    skippableAfterMs: 3000,
  },
  {
    id: "library-category-list",
    screen: "library",
    anchor: "library-category-list",
    title: "Categories",
    body: "Selectionne une categorie.",
    placement: "top",
    nextActionHint: "Clique une carte.",
    skippableAfterMs: 3000,
  },

  // Manage
  {
    id: "manage-title",
    screen: "manage",
    anchor: "manage-title",
    title: "Gerer",
    body: "Details d'une categorie.",
    placement: "bottom",
    nextActionHint: "Regarde l'entete.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-name",
    screen: "manage",
    anchor: "manage-category-name",
    title: "Categorie",
    body: "Nom de la categorie active.",
    placement: "bottom",
    nextActionHint: "Identifie la categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-back",
    screen: "manage",
    anchor: "manage-back",
    title: "Retour",
    body: "Reviens a la bibliotheque.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-card",
    screen: "manage",
    anchor: "manage-category-card",
    title: "Parametres",
    body: "Infos de la categorie.",
    placement: "top",
    nextActionHint: "Ouvre les parametres.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-settings",
    screen: "manage",
    anchor: "manage-category-settings",
    title: "Reglages categorie",
    body: "Ouvre les actions rapides.",
    placement: "left",
    nextActionHint: "Ouvre le menu.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-rename",
    screen: "manage",
    anchor: "manage-category-rename",
    title: "Renommer",
    body: "Change le nom.",
    placement: "right",
    nextActionHint: "Renomme si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-priority",
    screen: "manage",
    anchor: "manage-category-priority",
    title: "Prioritaire",
    body: "Definis la priorite.",
    placement: "right",
    nextActionHint: "Definis la priorite.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-category-delete",
    screen: "manage",
    anchor: "manage-category-delete",
    title: "Supprimer",
    body: "Action irreversible.",
    placement: "left",
    nextActionHint: "Utilise avec prudence.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-mini-why",
    screen: "manage",
    anchor: "manage-mini-why",
    title: "Mini-why",
    body: "Pourquoi de la categorie.",
    placement: "top",
    nextActionHint: "Lis ou modifie.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-mini-why-toggle",
    screen: "manage",
    anchor: "manage-mini-why-toggle",
    title: "Afficher",
    body: "Montre ou masque le mini-why.",
    placement: "left",
    nextActionHint: "Toggle si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-objectives-section",
    screen: "manage",
    anchor: "manage-objectives-section",
    title: "Objectifs",
    body: "Liste des objectifs.",
    placement: "top",
    nextActionHint: "Ouvre un objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-objectives-create",
    screen: "manage",
    anchor: "manage-objectives-create",
    title: "Creer un objectif",
    body: "Ajoute un objectif.",
    placement: "bottom",
    nextActionHint: "Cree un objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-actions-section",
    screen: "manage",
    anchor: "manage-actions-section",
    title: "Actions",
    body: "Liste des actions.",
    placement: "top",
    nextActionHint: "Ouvre une action.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-actions-create",
    screen: "manage",
    anchor: "manage-actions-create",
    title: "Creer une action",
    body: "Ajoute une action.",
    placement: "bottom",
    nextActionHint: "Cree une action.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-pilotage-section",
    screen: "manage",
    anchor: "manage-pilotage-section",
    title: "Pilotage",
    body: "Ouvre la vue d'ensemble.",
    placement: "top",
    nextActionHint: "Va sur Pilotage.",
    skippableAfterMs: 3000,
  },
  {
    id: "manage-open-pilotage",
    screen: "manage",
    anchor: "manage-open-pilotage",
    title: "Ouvrir pilotage",
    body: "Acces a la page Pilotage.",
    placement: "bottom",
    nextActionHint: "Ouvre Pilotage.",
    skippableAfterMs: 3000,
  },

  // Create hub
  {
    id: "create-title",
    screen: "create",
    anchor: "create-title",
    title: "Creer",
    body: "Choisis une etape.",
    placement: "bottom",
    nextActionHint: "Selectionne une carte.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-back",
    screen: "create",
    anchor: "create-back",
    title: "Retour",
    body: "Retour a la bibliotheque.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-step-category",
    screen: "create",
    anchor: "create-step-category",
    title: "Etape 1",
    body: "Cree une categorie.",
    placement: "top",
    nextActionHint: "Choisis categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-open-category",
    screen: "create",
    anchor: "create-open-category",
    title: "Ouvrir",
    body: "Accede au formulaire.",
    placement: "left",
    nextActionHint: "Ouvre categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-step-goal",
    screen: "create",
    anchor: "create-step-goal",
    title: "Etape 2",
    body: "Cree un objectif.",
    placement: "top",
    nextActionHint: "Choisis objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-open-goal",
    screen: "create",
    anchor: "create-open-goal",
    title: "Ouvrir",
    body: "Accede au formulaire.",
    placement: "left",
    nextActionHint: "Ouvre objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-step-action",
    screen: "create",
    anchor: "create-step-action",
    title: "Etape 3",
    body: "Cree une action.",
    placement: "top",
    nextActionHint: "Choisis action.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-open-action",
    screen: "create",
    anchor: "create-open-action",
    title: "Ouvrir",
    body: "Accede au formulaire.",
    placement: "left",
    nextActionHint: "Ouvre action.",
    skippableAfterMs: 3000,
  },

  // Create category
  {
    id: "create-category-title",
    screen: "create-category",
    anchor: "create-category-title",
    title: "Creer une categorie",
    body: "Debut du formulaire.",
    placement: "bottom",
    nextActionHint: "Remplis les champs.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-back",
    screen: "create-category",
    anchor: "create-category-back",
    title: "Retour",
    body: "Retour au choix.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-name",
    screen: "create-category",
    anchor: "create-category-name",
    title: "Nom",
    body: "Donne un nom clair.",
    placement: "top",
    nextActionHint: "Saisis un nom.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-color",
    screen: "create-category",
    anchor: "create-category-color",
    title: "Couleur",
    body: "Choisis une couleur.",
    placement: "top",
    nextActionHint: "Selectionne une couleur.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-why",
    screen: "create-category",
    anchor: "create-category-why",
    title: "Mini-why",
    body: "Optionnel, mais utile.",
    placement: "top",
    nextActionHint: "Ecris si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-priority",
    screen: "create-category",
    anchor: "create-category-priority",
    title: "Prioritaire",
    body: "Marque la priorite.",
    placement: "right",
    nextActionHint: "Active si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-cancel",
    screen: "create-category",
    anchor: "create-category-cancel",
    title: "Annuler",
    body: "Abandonne la creation.",
    placement: "left",
    nextActionHint: "Annule si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-category-submit",
    screen: "create-category",
    anchor: "create-category-submit",
    title: "Creer",
    body: "Valide la categorie.",
    placement: "left",
    nextActionHint: "Cree la categorie.",
    skippableAfterMs: 3000,
  },

  // Create goal
  {
    id: "create-goal-title",
    screen: "create-goal",
    anchor: "create-goal-title",
    title: "Creer un objectif",
    body: "Debut du formulaire.",
    placement: "bottom",
    nextActionHint: "Remplis les champs.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-back",
    screen: "create-goal",
    anchor: "create-goal-back",
    title: "Retour",
    body: "Retour au choix.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-category",
    screen: "create-goal",
    anchor: "create-goal-category",
    title: "Categorie",
    body: "Choisis la categorie.",
    placement: "top",
    nextActionHint: "Selectionne une categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-title-input",
    screen: "create-goal",
    anchor: "create-goal-title-input",
    title: "Nom",
    body: "Donne un objectif clair.",
    placement: "top",
    nextActionHint: "Ecris un titre.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-deadline",
    screen: "create-goal",
    anchor: "create-goal-deadline",
    title: "Echeance",
    body: "Optionnel.",
    placement: "top",
    nextActionHint: "Ajoute une date.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-measure",
    screen: "create-goal",
    anchor: "create-goal-measure",
    title: "Mesure",
    body: "Choisis un type.",
    placement: "top",
    nextActionHint: "Choisis une mesure.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-target",
    screen: "create-goal",
    anchor: "create-goal-target",
    title: "Cible",
    body: "Valeur a atteindre.",
    placement: "top",
    nextActionHint: "Saisis une cible.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-priority",
    screen: "create-goal",
    anchor: "create-goal-priority",
    title: "Prioritaire",
    body: "Marque la priorite.",
    placement: "right",
    nextActionHint: "Active si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-cancel",
    screen: "create-goal",
    anchor: "create-goal-cancel",
    title: "Annuler",
    body: "Abandonne la creation.",
    placement: "left",
    nextActionHint: "Annule si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-goal-submit",
    screen: "create-goal",
    anchor: "create-goal-submit",
    title: "Creer",
    body: "Valide l'objectif.",
    placement: "left",
    nextActionHint: "Cree l'objectif.",
    skippableAfterMs: 3000,
  },

  // Create action
  {
    id: "create-action-title",
    screen: "create-action",
    anchor: "create-action-title",
    title: "Creer une action",
    body: "Debut du formulaire.",
    placement: "bottom",
    nextActionHint: "Remplis les champs.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-back",
    screen: "create-action",
    anchor: "create-action-back",
    title: "Retour",
    body: "Retour au choix.",
    placement: "bottom",
    nextActionHint: "Utilise Retour.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-category",
    screen: "create-action",
    anchor: "create-action-category",
    title: "Categorie",
    body: "Choisis la categorie.",
    placement: "top",
    nextActionHint: "Selectionne une categorie.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-goal",
    screen: "create-action",
    anchor: "create-action-goal",
    title: "Objectif",
    body: "Lie l'action a un objectif.",
    placement: "top",
    nextActionHint: "Selectionne un objectif.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-title-input",
    screen: "create-action",
    anchor: "create-action-title-input",
    title: "Nom",
    body: "Nom de l'action.",
    placement: "top",
    nextActionHint: "Ecris un titre.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-cancel",
    screen: "create-action",
    anchor: "create-action-cancel",
    title: "Annuler",
    body: "Abandonne la creation.",
    placement: "left",
    nextActionHint: "Annule si besoin.",
    skippableAfterMs: 3000,
  },
  {
    id: "create-action-submit",
    screen: "create-action",
    anchor: "create-action-submit",
    title: "Creer",
    body: "Valide l'action.",
    placement: "left",
    nextActionHint: "Cree l'action.",
    skippableAfterMs: 3000,
  },

  // Pilotage
  {
    id: "pilotage-title",
    screen: "pilotage",
    anchor: "pilotage-title",
    title: "Pilotage",
    body: "Resume global.",
    placement: "bottom",
    nextActionHint: "Regarde les sections.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-category-status",
    screen: "pilotage",
    anchor: "pilotage-category-status",
    title: "Etat des categories",
    body: "Liste et statut.",
    placement: "top",
    nextActionHint: "Lis une ligne.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-load",
    screen: "pilotage",
    anchor: "pilotage-load",
    title: "Charge",
    body: "Planifie vs termine.",
    placement: "top",
    nextActionHint: "Lis les chiffres.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-planifier-empty",
    screen: "pilotage",
    anchor: "pilotage-planifier-empty",
    title: "Planifier",
    body: "Action rapide si rien n'est planifie.",
    placement: "left",
    nextActionHint: "Ouvre la creation.",
    skippableAfterMs: 3000,
  },
  {
    id: "pilotage-discipline",
    screen: "pilotage",
    anchor: "pilotage-discipline",
    title: "Discipline",
    body: "Indicateurs sur 7 jours.",
    placement: "top",
    nextActionHint: "Observe les valeurs.",
    skippableAfterMs: 3000,
  },

  // Settings
  {
    id: "settings-title",
    screen: "settings",
    anchor: "settings-title",
    title: "Reglages",
    body: "Parametres de l'app.",
    placement: "bottom",
    nextActionHint: "Fais defiler.",
    autoAdvanceAfterMs: 2000,
    skippableAfterMs: 3000,
  },
  {
    id: "settings-theme",
    screen: "settings",
    anchor: "settings-theme",
    title: "Theme",
    body: "Change l'ambiance visuelle.",
    placement: "top",
    nextActionHint: "Choisis un theme.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-why",
    screen: "settings",
    anchor: "settings-why",
    title: "Pourquoi",
    body: "Modifie ton engagement.",
    placement: "top",
    nextActionHint: "Edite ton pourquoi.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-replay-onboarding",
    screen: "settings",
    anchor: "settings-replay-onboarding",
    title: "Revoir l'intro",
    body: "Relance l'onboarding.",
    placement: "top",
    nextActionHint: "Relance l'intro.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-restart-tutorial",
    screen: "settings",
    anchor: "settings-restart-tutorial",
    title: "Relancer le tutoriel",
    body: "Rejoue le guide in-app.",
    placement: "top",
    nextActionHint: "Relance le tutoriel.",
    skippableAfterMs: 3000,
  },
  {
    id: "settings-notifications",
    screen: "settings",
    anchor: "settings-notifications",
    title: "Notifications",
    body: "Infos sur les alertes.",
    placement: "top",
    nextActionHint: "Lis l'information.",
    skippableAfterMs: 3000,
  },
];

const FIRST_USE_TOUR_STEP_IDS = [
  "today-title",
  "today-empty-create-category",
];

export const FIRST_USE_TOUR_STEPS = FIRST_USE_TOUR_STEP_IDS
  .map((id) => TOUR_STEPS.find((step) => step.id === id))
  .filter(Boolean);
