create table if not exists public.ai_request_logs (
  id bigint generated by default as identity primary key,
  request_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  coach_kind text not null check (coach_kind in ('now', 'recovery')),
  route text not null,
  plan_tier text not null check (plan_tier in ('free', 'premium')),
  decision_source text,
  status_code integer not null,
  request_hash text,
  ip_hash text,
  user_agent text,
  latency_ms integer,
  error_code text,
  created_at timestamptz not null default now()
);

comment on table public.ai_request_logs is 'Append-only AI usage log for quotas, abuse detection and debugging.';

create unique index if not exists ai_request_logs_request_id_uidx
  on public.ai_request_logs (request_id);

create index if not exists ai_request_logs_user_created_at_idx
  on public.ai_request_logs (user_id, created_at desc);

create index if not exists ai_request_logs_coach_created_at_idx
  on public.ai_request_logs (coach_kind, created_at desc);

alter table public.ai_request_logs enable row level security;
